#!/usr/bin/env bash

[[ $# -lt 1 ]] && echo "$(basename $0) domain.com [pfx]" && exit 1

openssl req \
       -newkey rsa:2048 -nodes -keyout ${1}.key \
       -x509 -days 365 -out ${1}.crt

[[ $2 == pfx ]] && openssl pkcs12 -export -out ${1}.pfx -inkey ${1}.key -in ${1}.crt
