---
release_to_repos:
  stage: push_release
  cache: {}
  script:
    - scl enable rh-python36 "python setup.py sdist"
    - pulp-admin python repo upload
        --repo-id ${CI_PROJECT_NAME//-/_}
        -f dist/${CI_PROJECT_NAME//-/_}-${CI_COMMIT_TAG}.tar.gz
    - pulp-admin python repo publish run --repo-id ${CI_PROJECT_NAME//-/_}
  only:
    - tags
  tags:
    - build_python
...
