#!/bin/bash


[[ $1 == "-h" ]] && echo "Usage example : ntimes 100 -- curlb 'http://ip.clara.net/'| percentile" && \
                     echo "https://github.com/yuya-takeyama/percentile" && \
                     echo "https://github.com/yuya-takeyama/ntimes" && \
                     exit 0

curl -s -o /dev/null -w '%{time_starttransfer}\n' "$@"
